### ISSUE TITLE
How safe is this to modify AST?

### ISSUE THREAD

**Issue by brinza888** [alexmojaki/executing#77]
If I am understand README well, this module uses tricks and modifications in AST to detect correct attribute nodes. So how safe are these modifications for runtime and correct execution?
This is actual question since you use `executing` in `icecream`, which one looks like just logging tool, but in fact everything goes to AST modifications to inspect variable names, function calls and list/dict elements access.

UPD. Sorry for opening Issues in both `executing` and `icecream`, maybe this can be useful for issue/questions archive in both of your projects.

**Comment by alexmojaki** [comment]
It's perfectly safe. When the README says "modify the AST" it doesn't mean modifying something that's directly linked to the bytecode being interpreted at runtime, which is simply not possible. The source code was parsed into a fresh AST object. I just say "the AST" because parsing the same source code produces an identical-looking AST.

**Comment by brinza888** [comment]
Well, now it is clear for me. Thank you for the answer!
